global: 
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates:
  - '/etc/alertmanager/template/alert.tmpl'

route:
  group_by: ['alertname']
  group_interval: 1m
  # 重复发送通知的间隔时间
  repeat_interval: 5m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'alerts@example.org'
      html: '{{ template "email.alert.html" . }}'
      headers: { Subject: 'Project name : {{ template "__subject" . }}' }
      send_resolved: true
