global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 4s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['hpbmon_server_alertmanager:9093']

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'host_exporter'
    static_configs:
    - targets: ['192.168.70.128:9100']
    metrics_path: "/metrics"

  - job_name: 'hpb_exporter'
    static_configs:
    - targets: ['192.168.70.128:9101']
    metrics_path: "/metrics/ghpb"
