{
 "title": "Summary Dashboard",
 "description": "Summary Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "每分钟的 CPU 平均利用率" }
   ],
   "targets": [
    {
     "expr": "100 - (avg without(cpu)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Disk Usage" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "memory total" },
    { "expr": "node_memory_Buffers_bytes{}", "legendFormat": "memory buffers" },
    { "expr": "node_memory_Cached_bytes{}", "legendFormat": "memory cached" },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Miner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "HPB_Mining{}" }
   ]
  },
  {
   "title": "Mining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "HPB_Mining{}" }
   ]
  },
  {
   "title": "GHPB",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "HPB_VERSION{}" }
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "content": "<center>\n<h2>Chain Name</h2>\n<br><br>\n<h1>$ChainName</h1>\n</center>"
    }
   ]
  },
  {
   "title": "BoeVersion",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "HPB_VERSION{}" }
   ]
  },
  {
   "title": "BlockNumber",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "HPB_BLOCKNUMBER{}" }
   ]
  },
  {
   "title": "PeersCount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "HPB_PEERCOUNT{}" }
   ]
  }
 ]
}